In [1]:
# Given a string, find all bigram and their counts

def bigram_count(string):
    string_list = string.split()
    d = {}
    for i in range(len(string_list)-1):
        if tuple(string_list[i:i+2]) in d:
            d[tuple(string_list[i:i+2])] += 1
        else:
            d[tuple(string_list[i:i+2])] = 1
    return d

string = "the quick person did not realize his speed and the quick person bumped "
bigram_count(string)

{('the', 'quick'): 2,
 ('quick', 'person'): 2,
 ('person', 'did'): 1,
 ('did', 'not'): 1,
 ('not', 'realize'): 1,
 ('realize', 'his'): 1,
 ('his', 'speed'): 1,
 ('speed', 'and'): 1,
 ('and', 'the'): 1,
 ('person', 'bumped'): 1}

In [ ]:
# Find the two largest numbers in a array of integers

def find_two_largest(arr):
    import numpy as np
    largest = -np.inf
    second_largest = -np.inf

    for item in arr:
        if item > largest:
            second_largest = largest
            largest = item
        elif item > second_largest:
            second_largest = item
    return [largest, second_largest]

In [2]:
# ['15min', '20 min', '40 minutes'], extract the number from it

def extract_numbers(strings):
    numbers = []
    for s in strings:
        number = ''
        for char in s:
            if char.isdigit():
                number += char
            elif number:
                numbers.append(int(number))
                number = ''
    if number:
        numbers.append(int(number))
    return numbers


strings = ['15min', '20 min', '40 minutes']
extract_numbers(strings)

[15, 20, 40]

In [12]:
# Fibonacci with memo - bottom up

def fib(n):
    if n == 1 or n == 2:
        return 1
    memo = []
    memo.append(1)
    memo.append(1)
    for i in range(2,n):
        next = memo[i-2]+memo[i-1]
        memo.append(next)
    return memo[-1]

fib(10)

55

In [11]:
# Fibonacci with memo - top down

def fib_with_memo(n):
    memo = {}
    def fib(n, memo):
        if n==1 or n==2:
            result = 1
        elif n in memo:
            result = memo[n]
        else:
            result = fib(n-1, memo) + fib(n-2, memo)
        memo[n] = result
        return result
    return fib(n, memo)

fib_with_memo(10)

55

In [15]:
# 0-1 knapsack problem
# description: give a list of items with weights and corresponding values
# you have a container with a weight limit
# select the items such that the total weights within the limit of container and the total value is maximized
# both time and space complexity is O(n * w_max)

In [21]:
# dynamic programming

def knapsack(w, v, w_max, n):
    dp = [[0 for x in range(w_max+1)] for x in range(n+1)]

    for i in range(n+1):
        for j in range(w_max+1):
            if i == 0 or j == 0:
                dp[i][j] = 0
            elif w[i-1] <= j:
                dp[i][j] = max(dp[i-1][j], v[i-1]+dp[i-1][j-w[i-1]])
            else:
                dp[i][j] = dp[i-1][j]
    return dp[n][w_max]


w = [10, 20, 30]
v = [60, 100, 120]
w_max = 50
n = len(v)
print(knapsack(w, v, w_max, n))

220

In [24]:
# Minimize cost of painting N houses such that adjacent houses have different colors
# Given an integer N and a 2D array cost, where cost[i][0], cost[i][1], and cost[i][2] is the cost of painting ith house with colors red, blue, and green respectively
# Find the minimum cost to paint all the houses such that NO two adjacent houses have the same color

# time-complexity: O(n), space-complexity: O(1)

def minCostToPaintHouses(cost):
    if not cost:
        return 0

    # Copy the first house's cost
    dp = cost[0]

    # Iterate over each house starting from the second one
    for i in range(1, len(cost)):
        # Current house cost when painted with red, blue, or green
        curr_red = cost[i][0] + min(dp[1], dp[2])
        curr_blue = cost[i][1] + min(dp[0], dp[2])
        curr_green = cost[i][2] + min(dp[0], dp[1])

        # Update dp with the current house's costs
        dp = [curr_red, curr_blue, curr_green]

    # The minimum cost will be the smallest cost of painting the last house
    return min(dp)


# Example usage:
cost = [[17, 2, 17], [16, 16, 5], [14, 3, 19], [2, 3, 8]]
print(minCostToPaintHouses(cost))

12

In [66]:
# TSP
# nearest insertion

import numpy as np

def find_nearest_unvisited(city, unvisited, distance_matrix):
    # Find the nearest unvisited city from the current city
    nearest_city = min(unvisited, key=lambda x: distance_matrix[city][x])
    return nearest_city, distance_matrix[city][nearest_city]

def find_insertion_position(city, tour, distance_matrix):
    # Find the position in the tour where inserting the city causes the least increase in length
    best_increase = float('inf')
    best_position = None
    for i in range(len(tour) - 1):
        current_increase = (distance_matrix[tour[i]][city] + 
                            distance_matrix[city][tour[i+1]] - 
                            distance_matrix[tour[i]][tour[i+1]])
        if current_increase < best_increase:
            best_increase = current_increase
            best_position = i + 1
    return best_position

def nearest_insertion(distance_matrix):
    # Start tour at the first city
    tour = [0, 0]  # start and end at the first city to make it a cycle
    unvisited = set(range(1, len(distance_matrix)))

    # Build the tour
    while unvisited:
        # Find the nearest unvisited city to the tour
        nearest_distance = float('inf')
        for city in tour:
            nearest_city, distance = find_nearest_unvisited(city, unvisited, distance_matrix)
            if distance < nearest_distance:
                nearest_distance = distance
                next_city = nearest_city

        # Find the best position to insert the next city
        insertion_position = find_insertion_position(next_city, tour, distance_matrix)
        tour.insert(insertion_position, next_city)
        unvisited.remove(next_city)

    # Calculate total cost of the tour
    total_cost = sum(distance_matrix[tour[i]][tour[i+1]] for i in range(len(tour)-1))

    return total_cost, tour

In [67]:
# Example distance matrix
distance_matrix = np.array([
    [0, 10, 15, 20],
    [10, 0, 35, 25],
    [15, 35, 0, 30],
    [20, 25, 30, 0]
])

cost, tour = nearest_insertion(distance_matrix)
print(f"Minimum cost: {cost}")
print(f"Tour: {tour}")

Minimum cost: 80
Tour: [0, 2, 3, 1, 0]

In [ ]:
################################################
# Data Wrangling using Python and SQL
################################################

In [ ]:
# two tables A and B, find the id's in A but not in B

# SQL
'''
select A.* 
from A
left join B
on A.id = B.id
where B.id is null
'''

In [28]:
# Pandas

import pandas as pd
import numpy as np

df_A = pd.DataFrame(
    {
        'id': [1, 2, 3, 4, 7],
        'col_a': [1, 1, 1 ,1, 1]
    }
)

df_B = pd.DataFrame(
    {
        'id':[1, 2, 3, 5, 6],
        'col_b': [1, 1, 1, 1, 1]
    }
)

df_1 = pd.merge(df_A, df_B, on = 'id', how='left')
df_2 = df_1[df_1['col_b'].isna()]
df_2

   id  col_a  col_b
3   4      1    NaN
4   7      1    NaN

In [68]:
# difference between merge, join, and concat
# Use merge when you need to align rows using one or more keys and perform SQL-like joins.
# Use join to combine DataFrames on the index (or on a key column), especially when you want to join on an index.
# Use concat when you want to stack multiple DataFrames on top of one another (vertically) or side by side (horizontally), and the alignment is not based on keys.

In [71]:
import pandas as pd
# merge

df_employees = pd.DataFrame({
    'emp_id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie']
})

df_salaries = pd.DataFrame({
    'emp_id': [1, 2, 4],
    'salary': [50000, 60000, 45000]
})

df_merged = pd.merge(df_employees, df_salaries, on='emp_id', how='inner')

df_merged

   emp_id   name  salary
0       1  Alice   50000
1       2    Bob   60000

In [72]:
# join

# Department data, indexed by dept_id
df_departments = pd.DataFrame({
    'dept_name': ['HR', 'Development', 'Sales']
}, index=[1, 2, 3])

# Assuming df_employees from the previous example is indexed by 'emp_id'
df_employees.set_index('emp_id', inplace=True)

# Join DataFrames on the index (department ID)
df_employees_with_dept = df_employees.join(df_departments)

In [75]:
df_employees_with_dept

           name    dept_name
emp_id
1         Alice           HR
2           Bob  Development
3       Charlie        Sales

In [80]:
# concat

df_jan_sales = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
    'sales': [200, 300, 400]
})

df_feb_sales = pd.DataFrame({
    'date': ['2023-02-01', '2023-02-02', '2023-02-03'],
    'sales': [250, 350, 450]
})

df_q1_sales = pd.concat([df_jan_sales, df_feb_sales], axis=0) # vertically
df_q1_sales

         date  sales
0  2023-01-01    200
1  2023-01-02    300
2  2023-01-03    400
0  2023-02-01    250
1  2023-02-02    350
2  2023-02-03    450

In [81]:
df_q1_sales = pd.concat([df_jan_sales, df_feb_sales], axis=1) # horizontally
df_q1_sales

         date  sales        date  sales
0  2023-01-01    200  2023-02-01    250
1  2023-01-02    300  2023-02-02    350
2  2023-01-03    400  2023-02-03    450

In [ ]:
# two tables
# driver_info: driver_id, age_range
# trip_info: driver_id, timestamp, trip_length
# find the total_trip_length and total_trip_count for driver in each age_range


# SQL
'''
select age_range,
       count(*) as total_trip_count,
       sum(trip_length) as total_trip_length
from
(select a.driver_id, a.trip_length, b.age_range
from trip_info a
left join driver_info b
on a.driver_id = b.driver_id) temp
group by age_range
'''


# pandas
'''
driver_df = driver_info[['driver_id', 'age_range']]
trip_df = trip_info[['driver_id', 'trip_length']]

df_1 = pd.merge(trip_df, driver_df, on='driver_id', how='left')
df_2 = df_1.groupby('age_range')['trip_length'].sum()
df_3 = df_1.groupby('age_range')['driver_id'].count()
'''

In [ ]:
# a table with three columns: group, id, amount
# calculate cumulative sum by group and order of id

# SQL
'''
select group,
       id,
       sum(amount) over (partition by group order by id) as cumlative_sum
from table
'''

# Pandas
'''
df_sorted = df.sort_values(by = ['group','id'], ascending = [True, True])
df_sorted['cumulative_sum'] = df_sorted.groupby('group')['amount'].cumsum()
'''

In [ ]:
# simulation

In [32]:
# generate random number by weights
# similar to LC528

def weighted_choice(numbers, weights):
    total_sum = 0
    cum_sum = []
    for weight in weights:
        total_sum += weight
        cum_sum.append(total_sum)
    
    import random
    target = total_sum*random.random()
    
    left = 0
    right = len(numbers)

    while left <= right:
        mid = (left+right)//2
        if cum_sum[mid] == target:
            return numbers[mid]
        elif cum_sum[mid] > target:
            right = mid-1
        else:
            left = mid+1
    return numbers[left]


# Example usage:
numbers = [10, 20, 30, 40, 50]
weights = [1, 2, 3, 4, 5]

weighted_choice(numbers, weights)

20

In [34]:
# Use biased coin to generate unbiased coin

weights = [0.3, 0.7]
options = ['head', 'tail']

import random
def weighted_choice(options, weights):
    return random.choices(options, weights=weights, k=2)

result = []

for i in range(100000):
    if weighted_choice(options, weights) == ['head', 'tail']:
        result.append('success')
    if weighted_choice(options, weights) == ['tail', 'head']:
        result.append('fail')

In [27]:
result.count('success')

21101

In [28]:
result.count('fail')

21038

In [29]:
# use dice to generate uniform distribution between 1 to 10
# rejection sampling

import random

def roll_die():
    return random.randint(1, 6)

def generate_uniform_distribution(lower, upper):
    roll_again = True
    while roll_again:
        first_roll = roll_die()-1
        second_roll = roll_die()-1    
        number = first_roll*6 + second_roll # 0 - 35
        if number >= lower and number <= upper:
            return number + 1

In [30]:
result = []

for i in range(500000):
    result.append(generate_uniform_distribution(0, 9))


for i in range(1,11):
    print('the occurance for {} is {}'.format(i, result.count(i)))

the occurance for 1 is 50288
the occurance for 2 is 49812
the occurance for 3 is 49974
the occurance for 4 is 50445
the occurance for 5 is 49709
the occurance for 6 is 50131
the occurance for 7 is 49847
the occurance for 8 is 50053
the occurance for 9 is 50008
the occurance for 10 is 49733

In [85]:
# Monty Hall probability simulation

import random

switch_true = []
switch_false = []

n = 100000
for i in range(n):
    items = ['goat', 'goat', 'car']
    random.shuffle(items)
    guest_select_idx = random.randint(0, 2)
    guest_select = items[guest_select_idx]
    switch_false.append(guest_select)

    items.pop(guest_select_idx)

    if items[0] == 'goat' and items[1] == 'goat':
        host_open_idx = random.randint(0,1)
    elif items[0] == 'goat':
        host_open_idx = 0
    else:
        host_open_idx = 1
    items.pop(host_open_idx)
    switch_true.append(items[0])

In [89]:
switch_true.count('car')/len(switch_true)

0.66871

In [90]:
switch_false.count('car')/len(switch_false)

0.33129

In [ ]:
# sorting

In [ ]:
# selection sort
# find the smallest of an array
# pop the element and find the smallest of the rest
# time-complexity O(n^2)
# space-complexity O(1) for in-place

In [54]:
def find_smallest(arr):
    import numpy as np
    smallest_num = arr[0]
    smallest_idx = 0
    for idx in np.arange(1,len(arr)):
        if arr[idx] < smallest_num:
            smallest_num = arr[idx]
            smallest_idx = idx
    return [smallest_num, smallest_idx]

def selection_sort(arr):
    if len(arr) <= 1:
        return arr
    sorted_arr = []
    while arr:
        sorted_arr.append(find_smallest(arr)[0])
        arr.pop(find_smallest(arr)[1])
    return sorted_arr

In [55]:
selection_sort([6,7,1,2,3,4,5,8,9,4,5])

[1, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9]

In [ ]:
# quick sort
# divide and conquer
# choose pivot and divide the array into two parts: greater than pivot value and smaller than pivot value
# time complexity: O(nlog(n)) on average, worst case is O(n^2)
# in worst case senario, the pivot is always the largest or smallest number
# space complexity: O(log(n)) on average for in-place, O(n) worst for in-place

In [56]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        less = [i for i in arr[1:] if i <= pivot]
        greater = [i for i in arr[1:] if i > pivot]
        return quick_sort(less) + [pivot] + quick_sort(greater)

In [57]:
quick_sort([6,7,1,2,3,4,5,8,9,4,5])

[1, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9]

In [ ]:
# merge sort
# divide and conquer
# time complexity O(nlog(n))
# space complexity O(n)
# recursively divide the array into two halves
# sort the two halves
# merge operation
# //: floor division
# %: modulus

In [35]:
def merge_sort(arr):
    if len(arr)<=1:
        return arr
    else:
        mid = len(arr)//2
        sorted_left = merge_sort(arr[:mid])
        sorted_right = merge_sort(arr[mid:])

        i, j, k = 0, 0, 0
        while i < len(sorted_left) and j < len(sorted_right):
            if sorted_left[i] <= sorted_right[j]:
                arr[k] = sorted_left[i]
                i+=1
                k+=1
            else:
                arr[k] = sorted_right[j]
                j+=1
                k+=1
        if i < len(sorted_left):
            arr[k:] = sorted_left[i:]
        else:
            arr[k:] = sorted_right[j:]
    return arr

In [38]:
merge_sort([6,7,1,2,3,4,5,8,9,4,5])

[1, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9]

In [1]:
# generate random distribution

import numpy as np
nums = np.random.normal(0, 1, 100) # mu, sigma

from scipy import stats
mu = 0
t_stat, p_value = stats.ttest_1samp(nums, mu)

In [5]:
print('the test statistics is {}'.format(t_stat))
print('the p-value is {}'.format(p_value))

the test statistics is -0.87531590955985
the p-value is 0.38352076279813896

In [6]:
# max running sum
def max_running_sum(arr):
    import numpy as np
    max_sum = -np.inf
    curr_sum = 0

    for i in range(len(arr)):
        curr_sum += arr[i]
        if curr_sum > max_sum:
            max_sum = curr_sum
    return max_sum


arr = [1, 2, 3, -4, -1, 3, 4, -1, -2]
max_running_sum(arr)

8

In [23]:
# Find the all the factors of a integer and calculate the sum 
def find_factors(num):
    left = 1
    right = num
    result = []

    while left < right:
        if num%left == 0:
            result.append(left)
            if num//left != left:
                result.append(num//left)
            right = num//left
        left = left+1
    return sorted(result)

find_factors(88)

[1, 2, 4, 8, 11, 22, 44, 88]

In [27]:
def find_factors(num):
    import numpy as np
    factors = []
    sqrt_num = int(np.sqrt(num))
    
    for i in range(1, sqrt_num + 1):
        if num % i == 0:
            factors.append(i)
            if i != num // i:
                factors.append(num // i)
    
    return sorted(factors)

find_factors(88)

[1, 2, 4, 8, 11, 22, 44, 88]

In [59]:
# extract IP address
import pandas as pd
import re
from collections import Counter

df = pd.DataFrame({
    'IP': ['fskjfklsdjflks 127.0.0.1 fsjkfjl', 'fsjlkfjls. fksj 256.111.111.1', '123.123.123.123 fsjdlfk.sfsdf.fs..sfdfd..sf.fkjskf']
})

def is_valid_ip(word):
    parts = word.split('.')
    if len(parts) != 4:
        return False
    for part in parts:
        if not part.isdigit() or not 0 <= int(part) <= 255:
            return False
    return True

all_ips = []
for row in df['IP']:
    words = row.split()
    for word in words:
        if is_valid_ip(word):
            all_ips.append(word)

ip_count = Counter(all_ips)
sorted_ip_count = sorted(ip_count.items(), key=lambda x: x[1], reverse=True)
for ip, count in sorted_ip_count:
    print(f'IP Address: {ip}, Frequency: {count}')

IP Address: 127.0.0.1, Frequency: 1
IP Address: 123.123.123.123, Frequency: 1

In [ ]:
# 在所有整数中找出满足一个数等于这个数所有的digit的五次方相加，比如abcd=a^5+b^5+c^5+d^5，然后把所有满足条件的数加起来求和

def sum_of_fifth_powers(n):
    return sum(int(digit)**5 for digit in str(n))

def find_special_numbers():
    limit = 9**5 * 6
    special_numbers = []
    for i in range(2, limit):
        if i == sum_of_fifth_powers(i):
            special_numbers.append(i)
    return special_numbers, sum(special_numbers)

special_numbers, total_sum = find_special_numbers()

In [94]:
# 一个k个元素的整数数列，随机sample一个点，然后改成NA，一直sample到全部数字都是NA

import random
import numpy as np
n = 100
arr = [random.randint(1,10) for _ in range(n)]

while arr.count(None) != n:
    idx = random.randint(0,n-1)
    arr[idx] = None

In [39]:
# sqrt(x)
# binary search

def mySqrt(x):
    if x<0:
        return 'please input another integer that is greater than 0'
    if x==0:
        return 0
    if x==1:
        return 1
    
    left = 0
    right = x

    while left <= right:
        mid = (left + right)//2
        if mid*mid == x:
            return mid
        elif mid*mid > x:
            right = mid - 1
        else:
            left = mid + 1
    return right

In [40]:
mySqrt(40)

6

In [46]:
# sqrt(x)
# netwon's method

def mySqrt(x):
    if x<0:
        return 'please input another integer that is greater than 0'
    if x==0:
        return 0
    if x==1:
        return 1
    
    p = 0
    n = x
    while abs(n-p)>0.1:
        p = n
        n = p - (p**2-x)/(2*p)
    
    return int(np.floor(n))